name: Terraform Validation

on:
  push:
    branches: [ github-refactor-best-practices ] #[ main, github-refactor-best-practices ]
  pull_request:
    types:
      - opened # necesario ?
      - reopened # necesario ?
      - synchronize
    branches: [ main ]

jobs:
  terraform-validation:
    uses: ./.github/workflows/terraform-common.yml
    with:
      terraform_fmt_version: 'latest'
      working_directory: '.'

