name: Terraform Validation

on:
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-fmt:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

  terraform-validation:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract Terraform min/max versions
      id: minMax
      uses: clowdhaus/terraform-min-max@v1.4.0

    - name: Setup Terraform (min version)
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ steps.minMax.outputs.minVersion }}

    - name: Terraform Init and Validate (min version)
      run: |
        terraform init
        terraform validate --color=always --show-diff-on-failure --files $(ls *.tf)

    - name: Setup Terraform (max version)
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ steps.minMax.outputs.maxVersion }}

    - name: Terraform Init and Validate (max version)
      run: |
        terraform init
        terraform validate --color=always --show-diff-on-failure --files $(ls *.tf)

