name: Terraform Validation

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches: 
      - main

jobs:
  terraform:
    uses: gocloudLa/.github/.github/workflows/terraform-module.yml@main
    with:
      terraform_fmt_version: 'latest'
      working_directory: '.'

